task: Imagenet
synthesizer: Pattern

data_path: /media/ssd/eugene/datasets/imagenet/

batch_size: 32
test_batch_size: 100
lr: 0.00001
momentum: 0.9
decay: 0.0005
epochs: 350
save_on_epochs: []
optimizer: Adam
log_interval: 100

scheduler: False
pretrained: True
max_batch_id: 1000
#resumed_model: model_image_Aug.15_11.40.44/model_last.pt.tar

#resumed_model: model_image_cifar_Oct.01_11.37.45/model_last.pt.tar

#resumed_model: ../../bd_proj/smoothing/models/cifar10/resnet110/noise_0.25/checkpoint.pth.tar

#resumed_model: model_image_Aug.31_17.16.10/model_last.pt.tar
#resumed_model: model_image_Sep.11_14.56.21/model_last.pt.tar # backdoored


poisoning_proportion: 0.5
backdoor_label: 8
backdoor: True

loss_balance: MGDA
mgda_normalize: none

save_model: False
log: False
tb: False

transform_train: True


loss_tasks:
  - backdoor
#  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed


#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588