task: Pipa
synthesizer: Pattern

batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 350
save_on_epochs: []
optimizer: SGD
log_interval: 100


scheduler: True

#resumed_model: model_image_Aug.15_11.40.44/model_last.pt.tar

#resumed_model: model_image_cifar_Oct.01_11.37.45/model_last.pt.tar

#resumed_model: ../../bd_proj/smoothing/models/cifar10/resnet110/noise_0.25/checkpoint.pth.tar

#resumed_model: model_image_Aug.31_17.16.10/model_last.pt.tar
#resumed_model: model_image_Sep.11_14.56.21/model_last.pt.tar # backdoored
#resumed_model: model_image_pipa_Mar.06_16.20.29/model_last.pt.tar

data_path: /media/hdd/eugene/backdoors/data/pipa/

poisoning_proportion: 1.1
backdoor_label: 1
backdoor: True

loss_balance: MGDA
mgda_normalize: loss


save_model: False
log: False
tb: False


loss_tasks:
  - backdoor
  - normal